server:
  port: 8080
spring:
  application:
    name: zull-api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
    ratingdataservice:
      url: http://localhost:8082/rating/getAllRatingData
#  employeeService:
#    path: /employee/**
#    url: http://localhost:8081
